/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.view;

import javax.swing.table.DefaultTableModel;
import app.controller.FacturaDaoImp;
import java.util.ArrayList;
import app.model.Factura;
import javax.swing.JOptionPane;
/**
 *
 * @author pigim
 */
public class FacturaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FacturaFrame.class.getName());
    private FacturaDaoImp factura = new FacturaDaoImp();
    /**
     * Creates new form FacturaFrame
     */
    public void cargarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tablafactura.getModel();
        modeloTabla.setRowCount(0);

        int[] anchos = {2, 70, 70, 70, 8, 8, 80, 50,30,30};
        for (int i = 0; i < tablafactura.getColumnCount(); i++) {
            tablafactura.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        factura.construirTabla(modeloTabla);

    }
    public FacturaFrame() {
        initComponents();
        cargarTabla();
        comboVentas();
    }
    
    
    
    public void comboVentas(){
       ArrayList<String> prueba = factura.Ventas();
       
       for(int i = 0; i < prueba.size();i++){
           jComboIDVENTA.addItem(prueba.get(i));
           System.out.println("ventas: "+prueba.get(i));
       }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboIDVENTA = new javax.swing.JComboBox<>();
        jTextNombre = new javax.swing.JTextField();
        jTextAPM = new javax.swing.JTextField();
        jTextAPP = new javax.swing.JTextField();
        jTextRFC = new javax.swing.JTextField();
        jTextRAZON = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDireccion = new javax.swing.JTextArea();
        jTextTotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablafactura = new javax.swing.JTable();
        JBtnGuardar = new javax.swing.JButton();
        JBtnEliminar = new javax.swing.JButton();
        JBtnModificar = new javax.swing.JButton();
        JBtnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("FACTURAS");

        jLabel2.setText("Id venta");

        jLabel3.setText("Apellido paterno");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido materno");

        jLabel6.setText("RFC");

        jLabel7.setText("Razon social");

        jLabel8.setText("Direccion fiscal");

        jLabel9.setText("Total");

        jComboIDVENTA.setFocusable(false);
        jComboIDVENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboIDVENTAActionPerformed(evt);
            }
        });

        jTextDireccion.setColumns(20);
        jTextDireccion.setRows(5);
        jScrollPane1.setViewportView(jTextDireccion);

        jTextTotal.setEditable(false);
        jTextTotal.setFocusable(false);

        tablafactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_factura", "id_venta", "Nombre", "Apellido Pat", "Apellido M", "RFC", "Razon", "Direcc", "fecha", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablafactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablafacturaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablafactura);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1071, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        JBtnGuardar.setText("Guardar");
        JBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnGuardarActionPerformed(evt);
            }
        });

        JBtnEliminar.setText("Eliminar");
        JBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEliminarActionPerformed(evt);
            }
        });

        JBtnModificar.setText("Modificar");
        JBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnModificarActionPerformed(evt);
            }
        });

        JBtnLimpiar.setText("Limpiar");
        JBtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jComboIDVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextAPM, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextAPP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextRAZON, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JBtnGuardar)
                                .addGap(37, 37, 37)
                                .addComponent(JBtnEliminar)
                                .addGap(26, 26, 26)
                                .addComponent(JBtnModificar))
                            .addComponent(JBtnLimpiar))))
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboIDVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextAPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextAPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextRAZON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnGuardar)
                    .addComponent(JBtnEliminar)
                    .addComponent(JBtnModificar))
                .addGap(36, 36, 36)
                .addComponent(JBtnLimpiar)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnGuardarActionPerformed
       
        if (jComboIDVENTA.getSelectedItem() == null
                || jComboIDVENTA.getSelectedItem().toString().trim().isEmpty()
                || jTextNombre.getText().trim().isEmpty()
                || jTextAPP.getText().trim().isEmpty()
                || jTextAPM.getText().trim().isEmpty()
                || jTextRFC.getText().trim().isEmpty()
                || jTextRAZON.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Se requieren todos los campos");

        } else {
            Factura fac = new Factura(Integer.parseInt(jComboIDVENTA.getSelectedItem().toString()),
                    jTextNombre.getText(),
                    jTextAPP.getText(),
                    jTextAPM.getText(),
                    jTextRFC.getText(),
                    jTextRAZON.getText(),
                    jTextDireccion.getText(),
                    factura.regresarTotal(Integer.parseInt(jComboIDVENTA.getSelectedItem().toString())));

            factura.GuardarFactura(fac);
            cargarTabla();
            limpiar();
        }
    }//GEN-LAST:event_JBtnGuardarActionPerformed

    private void JBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEliminarActionPerformed
        if (jComboIDVENTA.getSelectedItem() == null
                || jComboIDVENTA.getSelectedItem().toString().trim().isEmpty()
                || jTextNombre.getText().trim().isEmpty()
                || jTextAPP.getText().trim().isEmpty()
                || jTextAPM.getText().trim().isEmpty()
                || jTextRFC.getText().trim().isEmpty()
                || jTextRAZON.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Se requieren todos los campos");

        } else {
            int fila = tablafactura.getSelectedRow();
            int id = Integer.parseInt(tablafactura.getValueAt(fila, 0).toString());
            factura.EliminarFactura(id);
            cargarTabla();
            limpiar();
        }
    }//GEN-LAST:event_JBtnEliminarActionPerformed

    private void JBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnModificarActionPerformed
        if (jComboIDVENTA.getSelectedItem() == null
                || jComboIDVENTA.getSelectedItem().toString().trim().isEmpty()
                || jTextNombre.getText().trim().isEmpty()
                || jTextAPP.getText().trim().isEmpty()
                || jTextAPM.getText().trim().isEmpty()
                || jTextRFC.getText().trim().isEmpty()
                || jTextRAZON.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Se requieren todos los campos");

        } else {
            int fila = tablafactura.getSelectedRow();
            int id = Integer.parseInt(tablafactura.getValueAt(fila, 0).toString());
            Factura fac = new Factura(Integer.parseInt(jComboIDVENTA.getSelectedItem().toString()),
                    jTextNombre.getText(),
                    jTextAPP.getText(),
                    jTextAPM.getText(),
                    jTextRFC.getText(),
                    jTextRAZON.getText(),
                    jTextRAZON.getText(),
                    factura.regresarTotal(Integer.parseInt(jComboIDVENTA.getSelectedItem().toString())));
            factura.ModificarFactura(fac, id);
            cargarTabla();
            limpiar();
        }
    }//GEN-LAST:event_JBtnModificarActionPerformed

    private void JBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLimpiarActionPerformed

        limpiar();
    }//GEN-LAST:event_JBtnLimpiarActionPerformed

    private void tablafacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablafacturaMouseClicked
        int fila = tablafactura.getSelectedRow();
        int id = Integer.parseInt(tablafactura.getValueAt(fila, 0).toString());
        Factura fac = factura.ConsultarFactura(id);
        
        jComboIDVENTA.setSelectedItem(fac.getId_venta());
        jTextNombre.setText(fac.getNombre());
        jTextAPP.setText(fac.getApellido_paterno());
        jTextAPM.setText(fac.getApellido_materno());
        jTextRAZON.setText(fac.getRazon_social());
        jTextDireccion.setText(fac.getDireccion_fiscal());
        jTextRFC.setText(fac.getRfc());
        jTextTotal.setText(fac.getTotal()+"");
    }//GEN-LAST:event_tablafacturaMouseClicked

    private void jComboIDVENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboIDVENTAActionPerformed
        
        jTextTotal.setText(factura.regresarTotal(Integer.parseInt(jComboIDVENTA.getSelectedItem().toString()))+"");
    }//GEN-LAST:event_jComboIDVENTAActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        MenuFrame home = new MenuFrame();
        home.setVisible(true); 
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FacturaFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnEliminar;
    private javax.swing.JButton JBtnGuardar;
    private javax.swing.JButton JBtnLimpiar;
    private javax.swing.JButton JBtnModificar;
    private javax.swing.JComboBox<String> jComboIDVENTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextAPM;
    private javax.swing.JTextField jTextAPP;
    private javax.swing.JTextArea jTextDireccion;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextRAZON;
    private javax.swing.JTextField jTextRFC;
    private javax.swing.JTextField jTextTotal;
    private javax.swing.JTable tablafactura;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        jComboIDVENTA.setSelectedIndex(0);
        jTextNombre.setText("");
        jTextAPP.setText("");
        jTextAPM.setText("");
        jTextRAZON.setText("");
        jTextDireccion.setText("");
        jTextRFC.setText("");
        jTextTotal.setText("");
    }
}
